import type { KbPage } from "./types";

/**
 * SPOT.md — the canonical studio context document.
 * Derived from Spot Base pages (never stored separately), so there is one source of truth.
 * Structured for an LLM: stable headings, one section per page, metadata up top.
 */
export function buildSpotMd(pages: KbPage[], workspaceName = "Studio Spot") {
  const sorted = pages.slice().sort((a, b) => a.sort_order - b.sort_order);
  const updated = sorted.reduce((max, p) => (p.updated_at > max ? p.updated_at : max), "");
  const toc = sorted.map((p) => `- [${p.title}](#${p.slug})`).join("\n");
  const sections = sorted
    .map((p) => {
      // demote page headings one level so each page nests under its own H2
      const body = p.content_md.replace(/^(#{1,5}) /gm, "#$1 ").trim();
      return `<a id="${p.slug}"></a>\n## ${p.title}\n\n${body}`;
    })
    .join("\n\n---\n\n");
  return `# SPOT.md — ${workspaceName}

> Canonical context about ${workspaceName}. Generated by Spot OS from Spot Base.
> Last updated: ${updated ? updated.slice(0, 10) : "—"}. Edit the pages in Spot Base, not this file.

## Contents
${toc}

---

${sections}
`;
}
